// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebinarApiRest;

#nullable disable

namespace WebinarApiRest.Migrations
{
    [DbContext(typeof(WebinarDbContext))]
    [Migration("20221116195342_CustomerInitialData2")]
    partial class CustomerInitialData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebinarApiRest.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            FirstName = "Hugo",
                            LastName = "Vilchez"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            FirstName = "Bryan",
                            LastName = "Peralta"
                        },
                        new
                        {
                            Id = 3,
                            Age = 10,
                            FirstName = "Juan",
                            LastName = "Diaz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
